    function packagePayload(value){return{schema:"long-haul.course-package/1",packageId:value.packageId,seed:value.seed,generatorVersion:value.generatorVersion,routeField:{origin:value.origin,hub:value.hub,nodes:value.nodes,markers:[...value.nodes.map(node=>({id:node.id,kind:node.id==="origin"?"origin":"route-node",x:node.x,z:node.z})),...value.depots.map(depot=>({id:depot.id,kind:"depot",x:depot.x,z:depot.z,radius:depot.radius,metadata:{name:depot.name,branchId:depot.branchId}}))],corridors:value.edges,branches:value.branches,signs:value.signs},world:{cellSize:CELL_SIZE,activeRadius:ACTIVE_RADIUS,extent:"infinite",bounds:{mode:"infinite"},courseBounds:value.bounds,recipes:{wildlife:value.wildlife},initialPatches:[]},delivery:{candidateDepotIds:value.depots.map(d=>d.id),validDepotId:value.validDepotId},scoring:{parTimeSeconds:value.scoring.parTimeSeconds,parDistance:value.scoring.parDistance}}}
    const phases=["Choosing course","Building roads","Placing depots","Shaping terrain","Growing forests","Adding wildlife","Preparing truck","Checking course","Ready"];
    $("#phase-list").innerHTML=phases.map(phase=>`<div class="phase" data-phase="${phase}">${phase}</div>`).join("");
    function startGeneration(seed,reuseCourse=false,exitId="start"){if(generation&&!generation.ready&&!generation.error)return;const current=engine.n.coreScene.getCurrentScene()?.id;if(!["title","paused","results","loss","driving"].includes(current))return;clearWorld(false);resultTransitioned=false;lossTransitioned=false;lastDeliverySequence=0;lastPenaltyCount=0;activeContacts.clear();runSerial+=1;runKey=`${seed}:${runSerial}`;transition(exitId,{seed});generation={seed,reuseCourse:reuseCourse&&course,phaseIndex:0,initialCells:[],cursor:0,error:null};if(generation.reuseCourse)generation.generatedCourse=course;$("#course-code").textContent=`Course ${seedCode(seed)}`;updateLoadingUi()}
    function createResolvedCoursePatch(cell){const compiled=engine.n.longHaulWorldFeatures.compileCell(cell),samplers=engine.n.worldFeatures.getSamplers(),sampleHeight=(x,z)=>engine.n.worldFoundation.sampleElevation(cell.id,{x,z},samplers);return createCourseCellDescriptor(course,cell,{sampleHeight,foundationRevision:compiled.resolved?.revision??0})}
    function buildGenerationSteps(){const windowSize=(ACTIVE_RADIUS*2+1)**2;return[
      {phase:"Choosing course",run(){if(!generation.generatedCourse)generation.generatedCourse=generateCourse(engine,generation.seed);course=generation.generatedCourse;engine.n.longHaulWorldFeatures.loadCourse(course)}},
      {phase:"Building roads",run(){const payload=packagePayload(course);courseEnvelope=createLongHaulCourseEnvelope(engine,payload,{game:"The Long Haul"});verifyLongHaulCourseEnvelope(engine,courseEnvelope)}},
      {phase:"Placing depots",run(){engine.n.longHaulCourse.load(course);engine.n.longHaulDelivery.load(course.depots.map(d=>d.id),course.validDepotId)}},
      {phase:"Shaping terrain",run(){preparation=createLongHaulPatchPreparation(N,{id:`long-haul-${course.packageId}`,patchSize:CELL_SIZE,retainRadius:ACTIVE_RADIUS+1,prefetchDistance:3,cacheLimit:120,generationBudget:3,activationBudget:4,generatorVersion:course.generatorVersion,settingsHash:course.seed,generatePatch(request){return createResolvedCoursePatch(cellFromCoordinates(request.x,request.z))}});generation.initialCells=[];for(let z=-ACTIVE_RADIUS;z<=ACTIVE_RADIUS;z++)for(let x=-ACTIVE_RADIUS;x<=ACTIVE_RADIUS;x++)generation.initialCells.push(cellFromCoordinates(x,z));generation.initialCursor=0}},
      ...Array.from({length:windowSize},(_,index)=>({phase:index<Math.floor(windowSize*.45)?"Shaping terrain":"Growing forests",run(){const cell=generation.initialCells[generation.initialCursor++];const patch=createResolvedCoursePatch(cell);generation.initialPatches??=[];generation.initialPatches.push(patch)}})),
      {phase:"Adding wildlife",run(){engine.n.longHaulWildlife.load(course.wildlife)}},
      {phase:"Preparing truck",run(){const ground=engine.n.longHaulWorldFeatures.sampleElevationAt({x:course.origin.x,z:course.origin.z});engine.n.longHaulTruck.reset({x:course.origin.x,y:ground+.85,z:course.origin.z,heading:Math.PI});buildTruck();meters.reset();engine.n.longHaulRun.reset();engine.n.longHaulDelivery.reset();engine.n.longHaulDelivery.load(course.depots.map(d=>d.id),course.validDepotId);engine.n.longHaulWildlife.reset();engine.n.longHaulWildlife.load(course.wildlife)}},
      {phase:"Checking course",run(){for(const patch of generation.initialPatches){const [x,z]=patch.coordinates;preparation.prime({id:patch.cellId,x,z},patch)}engine.n.coreWorld.registerWorld({id:WORLD_ID,seed:course.seed,partition:N.createUniformGridPartition({cellSize:CELL_SIZE,radius:ACTIVE_RADIUS}),surface:N.createFlatWorldSurface(),providers:[createProvider()]});engine.n.coreWorld.setFocus(WORLD_ID,{position:{x:course.origin.x,y:0,z:course.origin.z}});engine.n.coreWorld.updateWorld(WORLD_ID);reconcileCells();const expected=(ACTIVE_RADIUS*2+1)**2;if(engine.n.coreWorld.getActiveCells(WORLD_ID).length!==expected)throw new Error("Initial world window did not activate cleanly");registerHorizonWorld();buildWildlife()}},
      {phase:"Ready",run(){document.body.classList.add("world-visible");engine.n.longHaulRun.start({x:course.origin.x,z:course.origin.z});meters.setLocked("remaining-time",false,"run-start");const state=engine.n.longHaulTruck.getState(),startHeading=state.heading,fx=Math.sin(startHeading),fz=Math.cos(startHeading);smoothing.snap("player-camera",{position:[course.origin.x-fx*28+3,15,course.origin.z-fz*28],lookPoint:[course.origin.x+fx*20,state.position.y+2.8,course.origin.z+fz*20],fov:59,mode:"chase"});transition("ready",{packageId:course.packageId});generation.ready=true}}
    ]}
    function stepGeneration(){if(!generation||generation.error||generation.ready)return;if(!generation.steps)generation.steps=buildGenerationSteps();const unit=generation.steps[generation.cursor];if(!unit)return;try{unit.run();generation.cursor+=1;generation.phaseIndex=phases.indexOf(unit.phase);updateLoadingUi()}catch(error){generation.error=error;showBootError(error)}}
    function updateLoadingUi(){const total=generation?.steps?.length||20;const done=generation?.cursor||0;const ratio=clamp(done/total,0,1);$("#progress-fill").style.width=`${Math.round(ratio*100)}%`;$("#progress-percent").textContent=`${Math.round(ratio*100)}%`;const phase=generation?.steps?.[generation.cursor]?.phase||"Ready";$("#phase-detail").textContent=phase;for(const element of $$(".phase")){const index=phases.indexOf(element.dataset.phase);element.classList.toggle("done",index<generation.phaseIndex||phase==="Ready");element.classList.toggle("active",element.dataset.phase===phase)}}

    function clearWorld(clearCourse=true){activeContacts.clear();clearHorizonWorld?.();try{if(engine.n.coreWorld.getWorld(WORLD_ID))engine.n.coreWorld.removeWorld(WORLD_ID)}catch{}for(const id of [...cellHosts.keys()])releaseCell(id);cellRoot.clear();dynamicRoot.clear();for(const id of ["tree-trunks","tree-crowns-a","tree-crowns-b","grass"]){try{batches.retainCells(id,[]);flushBatch(id)}catch{}}truckRig=null;wildlifeRig=null;preparation=null;lastCellKey="";mapOpen=false;updateMapPanel();document.body.classList.remove("world-visible","driving","final-minute");if(clearCourse){course=null;courseEnvelope=null;engine.n.longHaulWorldFeatures.reset()}engine.n.longHaulCourse.reset();engine.n.longHaulDelivery.reset();engine.n.longHaulWildlife.reset();engine.n.longHaulRun.reset();meters.reset()}

    const keys=Object.create(null),pressed=new Set();window.addEventListener("keydown",event=>{if(["ArrowUp","ArrowDown","ArrowLeft","ArrowRight","Space"].includes(event.code))event.preventDefault();keys[event.code]=true;if(!event.repeat)pressed.add(event.code);audio.ensure()},{passive:false});window.addEventListener("keyup",event=>{keys[event.code]=false});
    function consume(code){if(!pressed.has(code))return false;pressed.delete(code);return true}
