    function currentScene(){return engine.n.coreScene.getCurrentScene()?.id??"boot"}
    function surfaceAt(position){const road=nearestRoad(course,position);if(!road)return{surface:"off-road",grip:.38,road:null};const onRoad=road.distance<=road.edge.width*.55+1.4;const shoulder=road.distance<=road.edge.width*.85+5;return{surface:onRoad?"road":shoulder?"shoulder":"off-road",grip:onRoad?(road.edge.type==="rough-shortcut"?.72:1):shoulder?.62:.38,road}}
    function groundSample(position){const e=2,h=terrainHeight(course,position.x,position.z),left=terrainHeight(course,position.x-e,position.z),right=terrainHeight(course,position.x+e,position.z),back=terrainHeight(course,position.x,position.z-e),front=terrainHeight(course,position.x,position.z+e),nx=left-right,ny=e*2,nz=back-front,length=Math.hypot(nx,ny,nz)||1;return{height:h,normal:{x:nx/length,y:ny/length,z:nz/length}}}
    function preTickDriving(dt){const state=engine.n.longHaulTruck.getState();const run=engine.n.longHaulRun.getState();const condition={fuel:meters.get("fuel")?.value??0,truck:meters.get("truck-condition")?.value??0,cargo:meters.get("cargo-condition")?.value??0};const surface=surfaceAt(state.position),ground=groundSample(state.position);const throttle=(keys.KeyW||keys.ArrowUp)?1:0,brake=(keys.KeyS||keys.ArrowDown)?1:0,steer=((keys.KeyA||keys.ArrowLeft)?1:0)-((keys.KeyD||keys.ArrowRight)?1:0),handbrake=Boolean(keys.Space),boost=Boolean((keys.ShiftLeft||keys.ShiftRight)&&throttle&&condition.fuel>0);const steeringScale=settings.steering/100;engine.n.coreInput.setIntent({throttle,brake,steer:steer*steeringScale,handbrake,boost});engine.n.longHaulTruck.input({throttle:condition.fuel>0?throttle:0,brake,steer:steer*steeringScale,handbrake,boost,surface:surface.surface,surfaceGrip:surface.grip,groundHeight:ground.height,groundNormal:ground.normal});engine.n.longHaulCourse.sample(state.position);engine.n.longHaulRun.sample({position:state.position,speed:state.speed,surface:surface.surface,trying:Boolean(throttle||brake)});if(run.status==="running"){const fuelCost=(.014+Math.abs(state.speed)*.0018+throttle*.026+(boost?.12:0))*dt;meters.spend("fuel",fuelCost,"truck-motion")}if(surface.surface==="off-road"&&Math.abs(state.speed)>15){const op=`off-road:${Math.floor(state.position.x/38)}:${Math.floor(state.position.z/38)}`;const result=applyLongHaulOperationOnce(engine,runKey,op,()=>({seconds:8}));if(result.applied){engine.n.longHaulRun.penalty({id:op,kind:"off-road",label:"Hard off-road impact",seconds:8,collision:true});meters.spend("truck-condition",5,"off-road");meters.spend("cargo-condition",3,"off-road");engine.n.longHaulTruck.impulse({speedDelta:-state.speed*.3,y:1.2});toast("Hard off-road impact · +8s","bad");audio.hit()}}
      if(consume("KeyC")){cameraMode=(cameraMode+1)%2;engine.n.coreCamera.configure({mode:cameraMode?"hood":"chase"});audio.click()}
      if(consume("KeyM")){mapOpen=!mapOpen;updateMapPanel();audio.click()}
      if(consume("Escape")){pauseGame();return surface}
      if(consume("KeyR")){retrySame();return surface}
      if(consume("KeyE"))handleInteraction(state,run,condition,surface);
      updateCameraTarget(state,surface);return surface}
    function preTickIdle(){engine.n.coreInput.setIntent({throttle:0,brake:0,steer:0,handbrake:false,boost:false});const state=engine.n.longHaulTruck.getState(),ground=course?groundSample(state.position):{height:state.position.y,normal:{x:0,y:1,z:0}};engine.n.longHaulTruck.input({throttle:0,brake:0,steer:0,handbrake:false,boost:false,surface:"road",surfaceGrip:1,groundHeight:ground.height,groundNormal:ground.normal})}
    function updateCameraTarget(state,surface){const forward={x:Math.sin(state.heading),z:Math.cos(state.heading)},right={x:forward.z,z:-forward.x};const speed=Math.hypot(state.velocity?.x??0,state.velocity?.z??0);let position,look,fov;if(cameraMode===0){let distance=27+clamp(speed/38,0,1)*7;const sideOffset=3.2,initialX=state.position.x-forward.x*distance+right.x*sideOffset,initialZ=state.position.z-forward.z*distance+right.z*sideOffset;for(const obstacle of activeObstacles){const abx=initialX-state.position.x,abz=initialZ-state.position.z,length2=abx*abx+abz*abz||1,t=clamp(((obstacle.x-state.position.x)*abx+(obstacle.z-state.position.z)*abz)/length2,0,1),px=state.position.x+abx*t,pz=state.position.z+abz*t;if(t>.08&&t<.98&&Math.hypot(obstacle.x-px,obstacle.z-pz)<obstacle.radius+1.4)distance=Math.min(distance,Math.max(15,distance*t-3))}const px=state.position.x-forward.x*distance+right.x*sideOffset,pz=state.position.z-forward.z*distance+right.z*sideOffset;position=[px,Math.max(state.position.y+11.8,terrainHeight(course,px,pz)+6.5)+clamp(speed/38,0,1)*2.5,pz];look=[state.position.x+forward.x*(20+speed*.3),state.position.y+2.8,state.position.z+forward.z*(20+speed*.3)];fov=58+clamp(speed/38,0,1)*7}else{position=[state.position.x+forward.x*4.6,state.position.y+3.2,state.position.z+forward.z*4.6];look=[state.position.x+forward.x*42,state.position.y+2.7,state.position.z+forward.z*42];fov=69}position[1]=Math.max(position[1],terrainHeight(course,position[0],position[2])+3.5);if(settings.motion&&surface.road?.edge.type==="rough-shortcut")position[1]+=Math.sin(performance.now()*.018)*.1*clamp(speed/25,0,1);smoothing.setTarget("player-camera",{position,lookPoint:look,fov,mode:cameraMode?"hood":"chase"})}
    function handleInteraction(state,run,condition,surface){const needsRecovery=run.stuckSeconds>2.8||condition.fuel<=0.01||(surface.surface==="off-road"&&Math.abs(state.speed)<.8);if(needsRecovery&&!run.recoveryUsed){const result=applyLongHaulOperationOnce(engine,runKey,"recovery",()=>({seconds:30}));if(result.applied){const safe=state.lastSafe;engine.n.longHaulTruck.teleport({x:safe.x,y:safe.y,z:safe.z,heading:safe.heading,speed:0});engine.n.longHaulRun.recovery(safe);engine.n.longHaulRun.penalty({id:"recovery",kind:"recovery",label:"Roadside recovery",seconds:30,collision:false});meters.restore("fuel",16,"recovery");meters.restore("truck-condition",8,"recovery");toast("Roadside recovery · +30s","bad",2600);audio.tone(180,.2,"triangle",.08)}return}const nearest=nearestDepot(course,state.position);if(!nearest||nearest.distance>nearest.depot.radius+6){toast("No receiving gate in range","bad",1400);audio.wrong();return}if(Math.abs(state.speed)>1.1){toast("Stop the truck at the gate","bad",1600);audio.wrong();return}engine.n.longHaulDelivery.check(nearest.depot.id)}