    const $=(selector)=>document.querySelector(selector);const $$=(selector)=>Array.from(document.querySelectorAll(selector));const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));const lerp=(a,b,t)=>a+(b-a)*t;const clone=(v)=>structuredClone(v);const finite=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
    const REQUIRED=["createEngine","defineDomainServiceKit","createCoreSceneKit","createCoreWorldDomain","createUniformGridPartition","createQuadtreePartition","createFlatWorldSurface","createCurvedHorizonSurface","defineWorldEffectProvider","createCoreInputKit","createCoreDataKit","createCoreSimulationKit","createCoreCameraKit","createCoreGraphicsKit","createCoreTransactionLedgerKit","createWorldPatchPreparationController","createSemanticWorldFeatureKit"];
    for(const name of REQUIRED)if(typeof N[name]!=="function")throw new Error(`Required NexusEngine export missing: ${name}`);

    const settings={sound:true,steering:100,quality:true,motion:true};
    try{Object.assign(settings,JSON.parse(localStorage.getItem("the-long-haul-settings-v2")||"{}"))}catch{}
    settings.sound=settings.sound!==false;settings.quality=settings.quality!==false;settings.motion=settings.motion!==false;settings.steering=clamp(finite(settings.steering,100),75,125);

    const scenes={boot:{kind:"web-canvas-scene",exits:{ready:{to:"title"}}},title:{kind:"web-canvas-scene",exits:{start:{to:"generating"},settings:{to:"settings"},how:{to:"how-to-play"}}},generating:{kind:"web-three-scene",exits:{ready:{to:"driving"},cancel:{to:"title"}}},driving:{kind:"web-three-scene",exits:{pause:{to:"paused"},retry:{to:"generating"},complete:{to:"results"},fail:{to:"loss"},title:{to:"title"}}},paused:{kind:"web-three-scene",exits:{resume:{to:"driving"},settings:{to:"settings"},retry:{to:"generating"},title:{to:"title"}}},results:{kind:"web-three-scene",exits:{retry:{to:"generating"},fresh:{to:"generating"},title:{to:"title"}}},loss:{kind:"web-three-scene",exits:{retry:{to:"generating"},fresh:{to:"generating"},title:{to:"title"}}},settings:{kind:"web-canvas-scene",exits:{title:{to:"title"},pause:{to:"paused"}}},"how-to-play":{kind:"web-canvas-scene",exits:{back:{to:"title"}}}};
    const inputKit=N.createCoreInputKit({id:"long-haul-input",initialState:{intent:{throttle:0,brake:0,steer:0,boost:false,handbrake:false,interact:false}},actions:{throttle:{},brake:{},steerLeft:{},steerRight:{},boost:{},handbrake:{},interact:{},camera:{},map:{},pause:{},retry:{}},bindings:{keyboard:{throttle:["KeyW","ArrowUp"],brake:["KeyS","ArrowDown"],steerLeft:["KeyA","ArrowLeft"],steerRight:["KeyD","ArrowRight"],boost:["ShiftLeft","ShiftRight"],handbrake:["Space"],interact:["KeyE"],camera:["KeyC"],map:["KeyM"],pause:["Escape"],retry:["KeyR"]}},createApi({baseApi}){return{setIntent(intent={}){return baseApi.update({intent:clone(intent)},"updated")},getIntent(){return clone(baseApi.getState().intent??{})}}}});
    const core=createLongHaulCoreKits(N,{seed:"long-haul-boot",timeLimitSeconds:TIME_LIMIT_SECONDS});
    const product=createLongHaulProductKits(N);
    const engine=N.createEngine({tick:{maxDelta:1/15,rejectReentry:true},kits:[N.createCoreSceneKit({scenes,initialSceneId:"boot"}),N.createCoreWorldDomain({childDomains:false}),inputKit,...core.kits,...product.kits]});

    let transitionSequence=0;function transition(exitId,payload={}){transitionSequence+=1;return engine.n.coreScene.requestTransition({exitId,payload:clone(payload),transitionId:`long-haul-${transitionSequence}`})}
    const meters=engine.n.coreSimulation.resources;const batches=engine.n.coreGraphics.instanceBatches;const smoothing=engine.n.coreCamera.smoothing;
    for(const batch of [{id:"tree-trunks",assetId:"pine-trunk",materialId:"trunk",capacity:2400},{id:"tree-crowns-a",assetId:"pine-a",materialId:"pine-a",capacity:2400},{id:"tree-crowns-b",assetId:"pine-b",materialId:"pine-b",capacity:2400},{id:"grass",assetId:"grass",materialId:"grass",capacity:7500}])if(!batches.hasBatch(batch.id))batches.createBatch({...batch,updateMode:"incremental"});

    const renderer=new THREE.WebGLRenderer({canvas:$("#game-canvas"),antialias:true,powerPreference:"high-performance",alpha:false});renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.96;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
    const scene=new THREE.Scene();scene.background=new THREE.Color(0x7895a0);scene.fog=new THREE.FogExp2(0x91a7a3,.00042);const camera=new THREE.PerspectiveCamera(58,1,.1,52000);camera.position.set(0,13,-27);
    const worldRoot=new THREE.Group();scene.add(worldRoot);const cellRoot=new THREE.Group();worldRoot.add(cellRoot);const dynamicRoot=new THREE.Group();worldRoot.add(dynamicRoot);
    const hemi=new THREE.HemisphereLight(0xcde5f2,0x4f573e,1.15);worldRoot.add(hemi);const sun=new THREE.DirectionalLight(0xffc977,2.2);sun.position.set(-120,210,-80);sun.castShadow=true;sun.shadow.mapSize.set(1536,1536);sun.shadow.camera.near=20;sun.shadow.camera.far=650;sun.shadow.camera.left=-190;sun.shadow.camera.right=190;sun.shadow.camera.top=190;sun.shadow.camera.bottom=-190;sun.shadow.bias=-.0002;worldRoot.add(sun,sun.target);
    const skyGeometry=new THREE.SphereGeometry(900,24,14);const skyMaterial=new THREE.ShaderMaterial({side:THREE.BackSide,depthWrite:false,uniforms:{topColor:{value:new THREE.Color(0x547d92)},horizonColor:{value:new THREE.Color(0xeeb777)},groundColor:{value:new THREE.Color(0x6e7662)},sunColor:{value:new THREE.Color(0xffdf9c)}},vertexShader:"varying vec3 vP;void main(){vP=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}",fragmentShader:"uniform vec3 topColor;uniform vec3 horizonColor;uniform vec3 groundColor;uniform vec3 sunColor;varying vec3 vP;void main(){vec3 n=normalize(vP);float h=n.y;vec3 c=mix(groundColor,horizonColor,smoothstep(-.16,.08,h));c=mix(c,topColor,smoothstep(.02,.75,h));float s=pow(max(0.0,dot(n,normalize(vec3(-.55,.32,-.77)))),180.0);c+=sunColor*s*.8;gl_FragColor=vec4(c,1.0);}"});const sky=new THREE.Mesh(skyGeometry,skyMaterial);sky.renderOrder=-100;worldRoot.add(sky);
    const cloudMaterial=new THREE.MeshLambertMaterial({color:0xf2ead8,transparent:true,opacity:.35,depthWrite:false});const cloudRoot=new THREE.Group();for(let c=0;c<18;c++){const cloud=new THREE.Group();const count=3+(c%4);for(let i=0;i<count;i++){const puff=new THREE.Mesh(new THREE.SphereGeometry(1,8,6),cloudMaterial);puff.position.set(i*3+(i%2)*1.2,Math.sin(i)*.5,0);puff.scale.set(3.2+(i%3),1.1+(i%2)*.4,1.5);cloud.add(puff)}cloud.position.set((c%6-2.5)*170,90+(c%3)*24,(Math.floor(c/6)-1)*250);cloud.scale.setScalar(1.4);cloudRoot.add(cloud)}worldRoot.add(cloudRoot);
